### ISSUE TITLE
Weirdness with gpQueues 

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#169] opened 2019-04-02 17:56 UTC
I am trying to look up the current threshold for a DAO in Alchemy, and my understanding is that this can/should be pulled from gpQueue, however in my local subgraph I only get one gpQueue entity from the subgraph even though there are two DAOs. 

Furthermore my understanding is that a proposal's organizationId should match the gpQueue's id, which I see is mostly the case but I am seeing one proposal in the DAO that has a different organizationId than all the rest, and which doesn't have a corresponding gpQueue, why would this be?

**Comment by orenyodfat** [comment] 2019-04-02 18:15
could you please write a test/script to reproduce it ?
are you using ganache with latest migration for these 2 daos or other setup?

**Comment by tibetsprague** [comment] 2019-04-02 18:17
Yes Ganache with 0.0.1-rc.14-v8

**Comment by orenyodfat** [comment] 2019-04-02 18:26
well, it looks like a bug ..as gpQueues is created only upon a proposal state change.
to confirm that ..try to boost or execute a proposal on the dao which does not have the gpQueue .
I guess you can assume that a dao which does not have gpQueue it threshold is 1 ..though it is not nice.
Will fix this issue.

I think the 2nd issue that you raised  re the organizationId is related .
thanks

**Comment by tibetsprague** [comment] 2019-04-02 18:29
@orenyodfat yup, boosting a proposal creates the gpQueue entity

**Comment by ben-kaufman** [comment] 2019-04-03 12:20
This basically happens because GP doesn't emit a `StateChanged` event when the proposal is created. Technically it should as there is a state change but maybe it's unnecessary because we have the proposal created event which makes it obvious. So one option is to change GP in Infra to emit the event and another option is to change the subgraph to handle the proposal event as a state change as well.

**Comment by orenyodfat** [comment] 2019-04-03 13:03
NewProposal event is like a state change.
No need additional event in gp .
It should be fixed at subgraph

**Comment by jellegerbrandy** [comment] 2019-04-03 13:03
There are other options as well:

(1) In the subgraph:  create a `gpQueue` entity for each scheme when it is registered  (which, to me, seems the correct place to do it)

(2) In the client: if we want to get the threshold, we query first the gpQueue entity, and if it does not exist, we use calculate the default "threshold when there are no proposals" value

I'd prefer option (1) ttthogh.

**Comment by jellegerbrandy** [comment] 2019-04-03 13:06
We may be interested in the trhreshold already before any proposal was ever created. In a sense, the queue already exists, it is just empty. (I know, it is alimit case, but it is the first case we encounter when starting a new DAO :-))

**Comment by jellegerbrandy** [comment] 2019-04-03 13:06
(I commented at the same time as oren, and his solution will probably work as well with the current alchemy, but I think mine is better :-))

**Comment by orenyodfat** [comment] 2019-04-03 13:39
i was referred to @ben-kaufman  comment re the need to change infra. 

I do think that it is cleaner to have the gpq in place even there is no any proposal yet ...
though doing that upon a register scheme event might not give a clean general solution  because : 
1. It will create redundant gpques for schemes which use other voting machines or do not use voting at all.
2. for now , on ARC , all  organizationIds are the hash(scheme,Avatar) .  In general ,one can create a a scheme which does use gp but does not use Avatar as the _organisation . in that case this scheme will have different organizationId. This info is not included upon the register event.

**Comment by jellegerbrandy** [comment] 2019-04-03 15:38
So, @ben-kaufman , just for my info and for future doc: what is the solution you have implemented?

**Comment by ben-kaufman** [comment] 2019-04-04 08:04
@jellegerbrandy adding this threshold update to the register scheme event is a bit problematic as I don't have the `organizationId`. For now I just added when the proposal is created.

**Closed** 2019-04-04 13:13 UTC
Labels: bug
